{
    "config": {
        "error": {
            "cannot_connect": "\u00c9chec de connexion",
            "invalid_auth": "Authentification non valide",
            "not_supported": "Seule l'API PrusaLink v2 est prise en charge",
            "unknown": "Erreur inattendue"
        },
        "step": {
            "user": {
                "data": {
                    "api_key": "Cl\u00e9 d'API",
                    "host": "H\u00f4te"
                }
            }
        }
    }
}