{
    "config": {
        "error": {
            "cannot_connect": "Sikertelen csatlakoz\u00e1s",
            "invalid_auth": "\u00c9rv\u00e9nytelen hiteles\u00edt\u00e9s",
            "not_supported": "Csak a PrusaLink API v2 t\u00e1mogatott",
            "unknown": "V\u00e1ratlan hiba t\u00f6rt\u00e9nt"
        },
        "step": {
            "user": {
                "data": {
                    "api_key": "API kulcs",
                    "host": "C\u00edm"
                }
            }
        }
    },
    "entity": {
        "sensor": {
            "printer_state": {
                "state": {
                    "cancelling": "\u00c9rv\u00e9nytelen\u00edt\u00e9sben",
                    "idle": "T\u00e9tlen",
                    "paused": "Sz\u00fcneteltetve",
                    "pausing": "Sz\u00fcneteltet\u00e9sben",
                    "printing": "Nyomtat\u00e1sban"
                }
            }
        }
    }
}