{
    "config": {
        "abort": {
            "already_configured": "Il servizio \u00e8 gi\u00e0 configurato",
            "reauth_successful": "La nuova autenticazione \u00e8 stata eseguita correttamente"
        },
        "error": {
            "cannot_connect": "Impossibile connettersi",
            "invalid_auth": "Autenticazione non valida",
            "unknown": "Errore imprevisto",
            "wrong_app": "Applicazione errata raggiunta. Per favore riprova",
            "zeroconf_failed": "Chiave API non trovata. Si prega di inserirla manualmente"
        },
        "step": {
            "reauth_confirm": {
                "description": "L'integrazione Radarr deve essere di nuovo autenticata manualmente con l'API Radarr.",
                "title": "Autentica nuovamente l'integrazione"
            },
            "user": {
                "data": {
                    "api_key": "Chiave API",
                    "url": "URL",
                    "verify_ssl": "Verifica il certificato SSL"
                },
                "description": "La chiave API pu\u00f2 essere recuperata automaticamente se le credenziali di accesso non sono state impostate nell'applicazione.\nLa chiave API pu\u00f2 essere trovata in Impostazioni > Generali nell'interfaccia Web di Radarr."
            }
        }
    },
    "issues": {
        "deprecated_yaml": {
            "description": "La configurazione di Radarr tramite YAML \u00e8 stata rimossa.\n\nLa configurazione YAML esistente \u00e8 stata importata automaticamente nell'interfaccia utente.\n\nRimuovere la configurazione YAML di Radarr dal file configuration.yaml e riavviare Home Assistant per risolvere il problema.",
            "title": "La configurazione YAML di Radarr \u00e8 stata rimossa"
        }
    },
    "options": {
        "step": {
            "init": {
                "data": {
                    "upcoming_days": "Numero dei prossimi giorni da visualizzare"
                }
            }
        }
    }
}